# Generated by Django 4.0 on 2023-01-19 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='demo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_created=True)),
                ('name', models.CharField(max_length=150)),
                ('age', models.IntegerField()),
                ('time', models.TimeField(auto_now_add=True)),
                ('description', models.TextField(max_length=500)),
                ('slug', models.SlugField()),
                ('number', models.PositiveIntegerField()),
                ('number2', models.IntegerField()),
            ],
        ),
    ]
